[profile.default]
solc = "0.8.30"
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
evm_version = "prague"

remappings = [
    "@gnosis.pm=node_modules/@gnosis.pm",
    "@openzeppelin=node_modules/@openzeppelin",
    "fx-portal=node_modules/fx-portal",
]