"""Summarize existing local evidence into compact, publishable references.

No network access or independent verification. Recollect inputs using README.md.
Raw inputs remain ignored; hashes identify the precise files summarized here.
"""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
inputs = {}


def read(name):
    content = (ROOT / name).read_bytes()
    inputs[name] = hashlib.sha256(content).hexdigest()
    return json.loads(content)


inventory = read("data/manifest.json")
lineage = read("data/tag-lineage/lineage.json")
proposals = read("onchain/data/point0_reconciliation.json")
timeline = read("onchain/data/timeline.json")
for proposal in proposals["proposals"]:
    proposal["terminalReferences"] = [
        {k: event[k] for k in ["block", "tx", "event", "logIndex"]}
        for event in timeline if event["event"] in ["ProposalExecuted", "ProposalCanceled"]
        and event["args"].get("proposalId") == proposal["proposalId"]
        and event["contract"] == proposal["governor"]]
routes = read("onchain/data/guard_configuration_from_calls.json")
roles = read("point-1/data/role-history/result.json")
events = read("point-1/data/role-history/events.json")
analysis = read("point-1/data/analysis.json")
enrichment = read("point-1/data/enrichment.json")
manifest = read("point-1/data/manifest.json")
addresses = dict(manifest["addresses"])
# This is a public voting-wrapper address, not an API credential.
addresses["votingWrapper"] = addresses.pop("token")
# Holder-level sample addresses are deferred to the voting-power follow-up.
addresses.pop("whale", None)
snapshots = []
for row in analysis["snapshots"]:
    params = dict(row["parameters"])
    params["votingWrapper"] = params.pop("token")
    snapshots.append({"block": row["block"], "timestamp": row["timestamp"],
                      "parameters": params, "minDelay": row["minDelay"],
                      # Holder-level voting power is deferred to the voting-power follow-up.
                      "treasuryOwner": row["treasuryOwner"],
                      "pastTotalSupply": row["supply"], "quorumPreviousBlock": row["quorumPreviousBlock"]})
tests = {}
for name in ["mechanism-tests.txt", "live-mechanism-tests-drpc.txt", "recovery-tests.txt",
             "proposal15-current-fork-test.txt"]:
    relative = "point-1/data/" + name
    content = (ROOT / relative).read_bytes()
    inputs[relative] = hashlib.sha256(content).hexdigest()
    text = content.decode()
    cases = re.findall(r"\[(PASS|FAIL[^\]]*)\] (test\w+)\(\)", text)
    tests[name] = {"cases": [{"name": name, "result": status} for status, name in dict.fromkeys(cases)],
                   "summary": re.findall(r"Suite result: .+", text)}
artifacts = {}
for number, item in analysis["artifacts"].items():
    artifacts[number] = {k: item[k] for k in ["localId", "onchainId", "recomputedOnchainId",
                        "descriptionEqual", "localCallCount", "onchainCallCount", "creationTransaction"]}
    artifacts[number]["differingCallIndices"] = [x["index"] for x in item["comparisons"] if not x["equal"]]
    artifacts[number]["execution"] = item["execution"]
result = {
    "method": "Derived reference index from saved review evidence; not a fresh chain check or independent proof. Raw inputs are local/ignored and recollectable with the retained scripts.",
    "sourceInventory": inventory, "tags": lineage["nodes"], "pin": roles["pin"], "addresses": addresses,
    "proposalInventory": proposals, "artifactComparisons": artifacts, "parameterSnapshots": snapshots,
    "roleHistory": {"eventCount": roles["roleEventCount"], "firstBlock": roles["firstRoleEventBlock"],
                    "deploymentBoundary": roles["deploymentBoundary"],
                    "roles": [{k: v for k, v in r.items() if k != "checks"} for r in roles["roles"]],
                    "events": events, "limitations": roles["limitations"]},
    "guardState": roles["guard"], "cmModules": roles["cmModules"], "guardConfiguration": routes,
    "sourceVerification": analysis["sourceVerification"],
    "deploymentMetadata": enrichment["code"], "sensitiveGuardChecks": enrichment["guardChecks"],
    "proposalStateSamples": enrichment["proposals"],
    "receiptChecks": {"count": len(analysis["receiptVerification"]),
                      "allMatched": all(x["valid"] for x in analysis["receiptVerification"])},
    "tests": tests, "inputSha256": inputs,
}
# Compact JSON keeps exact integers/addresses without publishing raw payload archives.
(ROOT / "evidence.json").write_text(json.dumps(result, indent=2) + "\n")
print(f"Wrote evidence.json ({(ROOT / 'evidence.json').stat().st_size} bytes)")

def txlink(tx):
    return f"[transaction](https://etherscan.io/tx/{tx})"


lines = ["# Compact evidence references", "",
         "Generated by [build_evidence_index.py](build_evidence_index.py) from local saved inputs. "
         "[evidence.json](evidence.json) retains exact values, IDs, event references, test names and input SHA-256 hashes. "
         "These are recorded results, not a fresh chain check. Raw data and verbose outputs remain local/ignored.", "",
         "## Source versions", "", "| Reference | Commit | Tag date |", "|---|---|---|"]
for node in lineage["nodes"]:
    lines.append(f"| {node['label']} | [{node['sha'][:8]}](https://github.com/valory-xyz/autonolas-governance/commit/{node['sha']}) | {node.get('tagDate') or 'Snapshot'} |")
lines += ["", "Regenerate exact diffs with [collect_inventory.py](collect_inventory.py) and "
          "[collect_tag_lineage.py](collect_tag_lineage.py). Inventory counts and scope are in `sourceInventory` in the JSON.", "",
          "## Pins and addresses", "",
          f"Ethereum governance pin: **{roles['pin']['number']:,}**, hash `{roles['pin']['hash']}`. "
          f"Proposal inventory ends at **{proposals['source_to_block']:,}**. "
          "[Committed collector pin](point-1/data/pin.json). Reads are historical, not current-state claims.", "",
          "| Contract | Address / verified source |", "|---|---|"]
for name in ["governor", "oldGovernor", "firstGovernor", "timelock", "cm", "guard", "oldGuard", "treasury", "votingWrapper", "ve"]:
    address = addresses[name]
    lines.append(f"| {name} | [{address}](https://etherscan.io/address/{address}#code) |")
lines += ["", "## Proposals", "",
          "Recorded selection: **12 proposals; 9 executed, 1 cancelled, 2 inferred defeated**. "
          "Defeat is inferred from ended voting with zero For and positive Against votes; it has no execution/cancellation transaction. "
          "Creation and terminal references are keyed by exact proposal ID in the JSON.", "",
          "| Proposal description | Recorded outcome | Creation | Terminal event |", "|---|---|---|---|"]
for proposal in proposals["proposals"]:
    title = proposal["title"].replace("|", "\\|").replace("\n", " ")
    terminal = ", ".join(txlink(e["tx"]) for e in proposal["terminalReferences"]) or "Inferred defeat"
    lines.append(f"| {title} | {proposal['status']} | {txlink(proposal['creation_tx'])} | {terminal} |")
lines += ["", "Artifact comparisons: proposals 12–16 match the local descriptions and ordered calls. "
          "Proposal 11 is a partial cross-repository artifact (16 local calls versus 22 executed); this difference alone is not a security issue. "
          "See `proposalInventory` and `artifactComparisons`; reproduce with [check_point0.py](onchain/check_point0.py) "
          "after collecting/decoding logs.", "", "## Governance activation and parameters", ""]
for number, artifact in artifacts.items():
    lines.append(f"- Proposal {number}: executed at block **{artifact['execution']['block']:,}**, {txlink(artifact['execution']['tx'])}.")
lines += ["", "`parameterSnapshots` records before/after activation and proposal-15 values. At the main pin: "
          "13,091-block voting delay; 19,636-block voting period; 157,092-second Governor execution delay; "
          "zero Timelock minimum; 250,000 × 10¹⁸ proposal threshold; quorum 10/100. "
          "Passing requires sufficient For votes for quorum and For > Against. "
          "[Collector](point-1/collect_chain.cjs); [reconciliation](point-1/analyze_evidence.cjs).", "",
          "## Roles and recovery", "",
          "31 role events were reconstructed from deployment through the pin and reconciled against contract reads. "
          "Operational role administration is `TIMELOCK_ADMIN_ROLE`. "
          "The JSON retains role members, administration, all 31 event references, deployment boundary and limitations. "
          "[Collector](point-1/collect_role_history.cjs); [interpretation and recovery conditions](point-1/ROLES_AND_RECOVERY.md).", "",
          "Pinned CM modules: Timelock only. Guard restrictions are enabled; the specified heartbeat is unknown. "
          "Neither reproduced lockout is active. Conditional recovery tests mock a defeated heartbeat and impersonate cooperating Safe owners locally; "
          "they do not establish operational availability.", "", "## Guard configuration", "",
          'Future CM work follows the [changes-focused boundary](README.md#cm-review-boundary). Mapping prior coverage to exact versions and assumptions remains open; these recorded checks do not imply a fresh audit of unchanged Safe/bridge behaviour. Broad revalidation and operational recovery runbooks are deferred, not completed.', "",
          "`guardConfiguration` preserves the recorded L1 routes and target/selector permissions with their execution transaction and block. "
          "This is reconstruction from successful calls, not full live-matrix or destination-chain verification. "
          "`sensitiveGuardChecks` records the sampled rejected settings selectors. "
          "[Reconstructor](onchain/reconstruct_guard.cjs); [remaining work](SUMMARY.md#2-guardcm-and-cross-chain-permissions).", ""]
for tx in sorted({row["tx"] for kind in ["routes", "permissions"] for row in routes[kind]}):
    lines.append(f"- Configuration {txlink(tx)}.")
lines += ["", "## Source verification", "",
          "`sourceVerification` records the Governor's 29 source-file matches, RPC/explorer runtime match and compiled executable comparison. "
          "Compiler-declared immutable slots and CBOR metadata are excluded; this is not constructor-byte equality. "
          "`deploymentMetadata` records compiler/build data and runtime hashes for current/old Governors and Timelock. "
          "The deployed Timelock differs from the checkout version. "
          "`receiptChecks` records 130 matched events. "
          "[Source collection](point-1/enrich_chain.cjs); [comparison](point-1/analyze_evidence.cjs); "
          "[verified-source links](#pins-and-addresses).", "", "## Test results", "",
          "Historical results extracted from saved outputs; `tests` retains every case name/result and `inputSha256` identifies the full output. "
          "The recovery suite includes the two inherited live tests, so the suites overlap.", "",
          "| Suite | Recorded result | Source |", "|---|---|---|",
          "| Local mechanisms | 5 passed | [GovernanceReview](point-1/tests/GovernanceReview.t.sol) |",
          "| Deployed mechanisms | 2 passed | [GovernanceLiveReview](point-1/tests/GovernanceLiveReview.t.sol) |",
          "| Recovery, including inherited cases | 9 passed | [GovernanceRecoveryReview](point-1/tests/GovernanceRecoveryReview.t.sol) |",
          "| Existing proposal-15 latest-fork suite | 4 passed, 2 failed | [Proposal15GovernorParamsTest](../../test/proposals/Proposal15GovernorParams.t.sol) |", "",
          "The last run used block 26,032,488; its pre-execution assumptions no longer held. "
          "P1-04 also identifies a quorum assertion reading the old snapshot. "
          "These findings do not reopen independent execution verification. "
          "[Reproduction instructions](README.md#4-reproduction).", "", "## Design and review sources", "",
          "- [Contract specification](../../docs/Specs%20of%20governance%20contracts_v1.1.0.pdf) and "
          "[governance process](../../docs/Governance_process.pdf); text extracted with [collect_design.py](point-1/collect_design.py). Diagrams were not reviewed as evidence.",
          "- [Vulnerability register](../../docs/Vulnerabilities_list_governance.md), "
          "[internal20](../../audits/internal20/README.md), [internal21](../../audits/internal21/README.md).",
          "- PRs " + ", ".join(f"[#{n}](https://github.com/valory-xyz/autonolas-governance/pull/{n})" for n in [178,187,199,200,209,232,233]) +
          "; [collector](point-1/collect_prs.py). Inline review threads were not included.", "",
          "## Reproduction and limits", "",
          "[README reproduction order](README.md#4-reproduction) regenerates ignored source/chain intermediates. "
          "The compact index checker works without those raw inputs; rebuilding this index requires them. "
          "Archived hashes identify the original inputs but are not proof of completeness or authenticity. "
          "RPC/explorer availability, log completeness and matching source dependencies remain assumptions. "
          "Receipt checks validate returned logs, not the absence of omitted events. "
          "A fresh clone contains references and reproduction code, not the original raw archive.", ""]
(ROOT / "EVIDENCE.md").write_text("\n".join(lines))
