name: Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install modules
      - name: Install modules
        run: yarn install

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint contracts/interfaces/*.sol contracts/*.sol contracts/test/*.sol

      # Compile the code and run tests and deploy script(s)
      - name: Run tests
        run: ./node_modules/.bin/hardhat test

      # Run hardhat coverage and upload codecov report
      - name: Solidity coverage summary
        run: ./node_modules/.bin/hardhat coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false